Select * from Schools;
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Barry University School of Podiatric Medicine', 'Miami Shores', 'Florida', 'Podiatric');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('California School of Podiatric Medicine', 'Oakland', 'California', 'Podiatric');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Des Moines University College of Podiatric Medicine and Surgery', 'Des Moines', 'Iowa', 'Podiatric');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Kent State University College of Podiatric Medicine', 'Indepedence', 'Ohio', 'Podiatric');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('New York College of Podiatric Medicine', 'New York', 'New York', 'Podiatric');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Temple University School of Podiatric Medicine', 'Philadelphia', 'Pennsylvania', 'Podiatric');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Western University College of Podiatric Medicine', 'Pomona', 'California', 'Podiatric');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Dr. Williams M. School College of Podiatric Medicine', 'North Chicago', 'Illinois', 'Podiatric');

INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Alabama School of Dentistry', 'Birmingham', 'Alabama', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Arizona School of Dentistry and Oral Health', 'Mesa', 'Arizona', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Midwestern University College of Dental Medicine', 'Glendale', 'Arizona', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of California, Los Angeles School of Dentistry', 'Los Angeles', 'California', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of California, San Francisco School of Dentistry', 'San Francisco', 'California', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Colorado School of Dental Medicine', 'Aurora', 'Colorado', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Connecticut School of Dental Medicine', 'Farmington', 'Connecticut', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Howard University College of Dentistry', 'Washington', 'DC', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('LECOM School of Dental Medicine', 'Bradenton', 'Florida', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Nova Southeastern University College of Dental Medicine', 'Ft. Lauderdale', 'Florida', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Florida College of Dentistry', 'Gainesville', 'Florida', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('The Dental College of Georgia at Augusta University', 'Augusta', 'Georgia', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Illinois at Chicago College of Dentistry', 'Chicago', 'Illinois', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Indiana University School of Dentistry', 'Indianapolis', 'Indiana', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('The University of Iowa College of Dentistry and Dental Clinics', 'Iowa City', 'Iowa', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Kentucky College of Dentistry', 'Lexington', 'Kentucky', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Louisville School of Dentistry', 'Louisville', 'Kentucky', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Louisiana State University Health Science Center School of Dentistry', 'New Orleans', 'Louisiana', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of New England College of Dental Medicine', 'Portland', 'Maine', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Universtiy of Maryland School of Dental Medicine', 'Baltimore', 'Maryland', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Boston University Henry M. Goldman School of Dental Medicine', 'Boston', 'Massachusetts', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Harvard School of Dental Medicine', 'Boston', 'Massachusetts', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Minnesota School of Dentistry', 'Minneapolis', 'Minnesota', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Mississippi Medical Center School of Dentistry', 'Jackson', 'Mississippi', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Missouri School of Dentistry and Oral Health at ATSU', 'Kirksville', 'Missouri', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Missouri-Kansas City School of Dentistry', 'Kansas City', 'Missouri', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Creighton University School of Dentistry', 'Omaha', 'Nebraska', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Nebraska Medical Center College of Dentistry', 'Lincoln', 'Nebraska', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Nevada, Las Vegas School of Dental Medicine', 'Las Vegas', 'Nevada', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Ruthers School of Dental Medicine', 'Newark', 'New Jersey', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Columbia University College of Dental Medicine', 'New York', 'New York', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('New York University College of Dentistry', 'New York', 'New York', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Universtiy at Buffalo School of Dental Medicine', 'Buffalo', 'New York', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('East Carolina University School of Dental Medicine', 'Greenville', 'North Carolina', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of North Carolina at Chapel Hill School of Dentistry', 'Chapel Hill', 'North Carolina', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Oklahoma College of Dentistry', 'Oklahoma City', 'Oklahoma', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Oregon Health Sciences University School of Dentistry', 'Portland', 'Oregon', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Pennsylvania School of Dental Medicine', 'Philadelphia', 'Pennsylvania', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Pittsburgh School of Dental Medicine', 'Pittsburgh', 'Pennsylvania', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Medical University of South Carolina College of Dental Medicne', 'Charleston', 'South Carolina', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Tennessee Health Science Center College of Dentistry', 'Memphis', 'Tennessee', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Meharry Medical College School of Dentistry', 'Nashville', 'Tennessee', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Texas A&M University College of Dentistry', 'Dallas', 'Texas', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Texas Health Science Center at San Antonio School of Dentistry', 'San Antonio', 'Texas', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Roseman Univesity of Health Sciences College of Dental Medicine', 'South Jordan', 'Utah', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Utah School of Dentistry', 'Salt Lake City', 'Utah', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Virginia Commonwealth University School of Dentistry', 'Richmond', 'Virginia', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Washington School of Dentistry', 'Seattle', 'Washington', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('West Virginia University School of Dentistry', 'Morgantown', 'West Virginia', 'Dental');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Marquette University School of Dentistry', 'Milwaukee', 'Wisconsin', 'Dental');

INSERT INTO Schools (School_Name, City, State, School_Type) values ('Edward Via College of Osteopathic Medicine', 'Auburn', 'Alabama', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('A.T. Still University School of Osteopathic Medicine in Arizona', 'Mesa', 'Arizona', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Midwestern University Arizona College of Osteopathic Medicine', 'Glendale', 'Arizona', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Arkansas College of Ostepathic Medicine', 'Fort Smith', 'Arkansas', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Touro University California College of Osteopathic Medicine', 'Vallejo', 'California', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Western University of Health Sciences College of Osteopathic Medicine of the Pacific', 'Pomona', 'California', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Rocky Vista University College of Osteopathic Medicine', 'Parker', 'Colorado', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Lake Erie College of Osteopathic Medicine', 'Bradenton', 'Florida', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Nova Southeastern University College of Osteopathic Medicine', 'Davie', 'Florida', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Philadelphia College of Osteopathic Medicine – Georgia Campus', 'Suwanee', 'Georgia', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Midwestern University Chicago College of Osteopathic Medicine', 'Downers Grove', 'Illinois', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Marian University College of Osteopathic Medicine', 'Indianapolis', 'Indiana', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Des Moines University College of Osteopathic Medicine', 'Des Moines', 'Iowa', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Pikeville Kentucky College of Osteopathic Medicine', 'Pikeville', 'Kentucky', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of New England College of Osteopathic Medicine', 'Biddeford', 'Maine', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Michigan State University College of Osteopathic Medicine', 'Detroit', 'Michigan', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('William Carey University College of Osteopathic Medicine', 'Hattiesburg', 'Mississippi', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('A.T. Still University Kirksville College of Osteopathic Medicine', 'Kirksville', 'Missouri', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Kansas City University of Medicine and Biosciences College of Osteopathic Medicine', 'Kansas City', 'Missouri', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Touro University Nevada College of Osteopathic Medicine', 'Henderson', 'Nevada', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Rowan University School of Osteopathic Medicine', 'Stratford', 'New Jersey', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Burrell College of Osteopathic Medicine at New Mexico State university', 'Las Cruces', 'New Mexico', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('New York Institute of Technology College of Osteopathic Medicine', 'Old Westbury', 'New York', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Touro College of Osteopathic Medicine', 'Manhattan', 'New York', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Campbell University School of Osteopathic Medicine', 'Buies Creek', 'North Carolina', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Ohio University Heritage College of Osteopathic Medicine', 'Cleveland', 'Ohio', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Oklahoma State University Center for Health Sciences College of Osteopathic Medicine', 'Tulsa', 'Oklahoma', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('College of Osteopathic Medicine of the Pacific Northwest', 'Lebanon', 'Oregon', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Philadelphia College of Osteopathic Medicine', 'Philadelphia', 'Pennsylvania', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Edward Via College of Osteopathic Medicine – Carolina’s Campus', 'Spartanburg', 'South Carolina', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Lincoln Memorial University DeBusk College of Osteopathic Medicine', 'Harrogate', 'Tennessee', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of the Incarnate Word School of Osteopathic Medicine', 'San Antonio', 'Texas', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of North Texas Health Science Center Texas College of Osteopathic Medicine', 'Fort Worth', 'Texas', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Rocky Vista University College of Osteopathic Medicine – Southern Utah Campus', 'Ivins', 'Utah', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Liberty University College of Osteopathic Medicine', 'Lynchburg', 'Virginia', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Pacific Northwest University of Health Sciences', 'Yakima', 'Washington', 'Osteopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('West Virginia School of Osteopathic Medicine', 'Lewisburg', 'West Virginia', 'Osteopathic');

INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Alabama School of Medicine', 'Birmingham', 'Alabama', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of South Alabama College of Medicine', 'Mobile', 'Alabama', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Mayo Medical School', 'Scottsdale', 'Arizona', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Arizona College of Medicine - Tuscon', 'Tuscon', 'Arizona', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Arkansas for Medical Sciences/UAMS College of Medicine', 'Little Rock', 'Arkansas', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of California, Davis School of Medicine', 'Sacramento', 'California', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of California, San Diego School of Medicine', 'San Diego', 'California', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Colorado School of Medicine', 'Aurora', 'Colorado', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Connecticut School of Medicine', 'Farmington', 'Connecticut', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Yale School of Medicine', 'New Haven', 'Connecticut', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('George Washington University Medical School', 'Washington', 'DC', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Florida State University College of Medicine', 'Tallahassee', 'Florida', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Florida College of Medicine', 'Gainesville', 'Florida', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Mercer University School of Medicine', 'Macon', 'Georgia', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Medical College of Georgia at Augusta University', 'Augusta', 'Georgia', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Illinois College of Medicine', 'Chicago', 'Illinois', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Indiana University School of Medicine', 'Indianapolis', 'Indiana', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Iowa Roy J. and Lucille A. Carver College of Medicine', 'Iowa City', 'Iowa', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Kansas School of Medicine', 'Kansas City', 'Kansas', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Kentucky College of Medicine', 'Louisville', 'Kentucky', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Louisiana State University School of Medicine in New Orleans', 'New Orleans', 'Louisiana', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('John Hopkins University School of Medicine', 'Baltimore', 'Maryland', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Boston Univeristy School of Medicine', 'Boston', 'Massachusetts', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Harvard Medical School', 'Boston', 'Massachusetts', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Massachusetts Medical School', 'Worcester', 'Massachusetts', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Michigan Medical School', 'Ann Arbor', 'Michigan', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Mayo Clinic College of Medicine', 'Rochester', 'Minnesota', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Minnesota Medical School', 'Minneapolis', 'Minnesota', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Mississippi School of Medicine', 'Jackson', 'Mississippi', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Saint Louis University School of Medicine', 'St. Louis', 'Missouri', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Missouri-Kansas City School of Medicine', 'Kansas City', 'Missouri', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Washington University School of Medicine', 'St. Louis', 'Missouri', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Nebraska College of Medicine', 'Omaha', 'Nebraska', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Nevada, Las Vegas School of Medicine', 'Las Vegas', 'Nevada', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Rutgers New Jersey Medical School', 'Newark', 'New Jersey', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of New Mexico School of Medicine', 'Albuquerque', 'New Mexico', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('New York University School of Medicine', 'Manhattan', 'New York', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('State University of New York Upstate Medical University', 'Syracuse', 'New York', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Albany Medical College', 'Albany', 'New York', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of North Carolina School of Medicine', 'Chapel Hill', 'North Carolina', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Duke University School of Medicine', 'Durham', 'North Carolina', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of North Dakota School of Medicine and Health Sciences', 'Grand Forks', 'North Dakota', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('The Ohio State University College of Medicine', 'Columbus', 'Ohio', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Oklahoma College of Medicine', 'Oklahoma City', 'Oklahoma', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Pennsylvania State University College of Medicine', 'Hershey', 'Pennsylvania', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Pittsburg School of Medicine', 'Pittsburg', 'Pennsylvania', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Medical University of South Carolina College of Medicine', 'Charleston', 'South Carolina', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Sanford School of Medicine of the University of South Dakota', 'Vermillion', 'South Dakota', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Tennessee College of Medicine', 'Memphis', 'Tennessee', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Texas Medical Branch School of Medicine', 'Galveston', 'Texas', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Utah School of Medicine', 'Salt Lake City', 'Utah', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Vermont College of Medicine', 'Burlington', 'Vermont', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Virginia School of Medicine', 'Charlottesville', 'Virginia', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('University of Washington School of Medicine', 'Seattle', 'Washington', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('West Virginia University School of Medicine', 'Morgantown', 'West Virginia', 'Allopathic');
INSERT INTO Schools (School_Name, City, State, School_Type) values ('Medical College of Wisconsin', 'Milwaukee', 'Wisconsin', 'Allopathic');